version: '3'

services:
  frontend:
    image: node:18-alpine
    container_name: atlas_frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules:
